name: Trigger auto deployment for devops-ipl

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ main ]
    paths:
    - '**'
    - '.github/workflows/devops-ipl-AutoDeployTrigger-cd5aa83c-6c70-40e2-a74f-6c74becbe6a4.yml'

  # Allow manual trigger 
  workflow_dispatch:      

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions: 
      id-token: write #This is required for requesting the OIDC JWT Token
      contents: read #Required when GH token is used to authenticate with private repo

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.DEVOPSIPL_AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.DEVOPSIPL_AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.DEVOPSIPL_AZURE_SUBSCRIPTION_ID }}

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v2
        with:
          appSourcePath: ${{ github.workspace }}/01-docker/web-app
          _dockerfilePathKey_: _dockerfilePath_
          registryUrl: vanshika.azurecr.io
          registryUsername: ${{ secrets.DEVOPSIPL_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.DEVOPSIPL_REGISTRY_PASSWORD }}
          containerAppName: devops-ipl
          resourceGroup: neilgogte
          imageToBuild: vanshika.azurecr.io/devops-ipl:${{ github.sha }}
          _buildArgumentsKey_: |
            _buildArgumentsValues_


